name: build-and-deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: Build the project
      run: npm run build

    - name: List workspace contents for debugging
      run: ls -la

    - name: List build directory contents for debugging
      run: ls -la build

    - name: Deploy to GitHub Pages
      uses: bitovi/github-actions-react-to-github-pages@v1.2.4
      with:
        path: build
